### Atelier Pandas

##### Contexte 
Une entreprise possède plusieurs bâtiments équipés de capteurs IoT. 
Chaque capteur collecte régulièrement des informations sur la température, l'humidité, la pression, 
la consommation énergétique, l'état du capteur, le bâtiment, la date et l'heure de la mesure. 
Les données doivent être préparées et analysées avant d'être transmises à un futur système de 
Machine Learning permettant de détecter des situations anormales.

##### Structuration du projet
        1) Structuration le projet 
        2) Stocker le fichier fourni mesures_capteurs.csv dans le sous-dossier data 
        3) Créer le notebook atelier_pandas_iot.ipynb

In [19]:
import pandas as pd

#### Partie 1 – Series

##### 1) Création d'une Series contenant 4 températures

In [20]:
serie_temp4 = pd.Series([12.25, 38.01, 5.8, 14.5])
serie_temp4

0    12.25
1    38.01
2     5.80
3    14.50
dtype: float64

##### 2) Affichage de l'index de la série

In [21]:
print("L'index de la séerie : ",serie_temp4.index)

L'index de la séerie :  RangeIndex(start=0, stop=4, step=1)

##### 3) Affichage de la 1ère valeur de la série

In [22]:
print("La 1ére valeur de la série est : ", serie_temp4[0])

La 1ére valeur de la série est :  12.25

##### 4) Affichage de la dernière valeur de la série

In [23]:
print("La dernière valeur de la série est : ", serie_temp4.iloc[-1])

La dernière valeur de la série est :  14.5

##### 5) Création de deux façon différentes, une Series de 4 températures avec comme index les heures de mesure 12h, 13h, 14h et 15h

In [ ]:
# Première maniére
serie_temp_h = pd.Series([21.5, 32, 7.03, 18], index=['12h', '13h', '14h', '15h'])

# Deuxiéme manière
dict = {'12h' : 21.5, '13h' : 32, '15h' : 7.03, '15h' : 18}
serie_temp_h = pd.Series(dict)
serie_temp_h

12h    21.5
13h    32.0
15h    18.0
dtype: float64

##### 6) Affichage la 1ère et la dernière valeur

In [34]:
# 1e valeur
print("La 1ére valeur de la série est : ", serie_temp_h['12h'])

# dernière valeur
print("La dernière valeur de la série est : ", serie_temp_h.iloc[-1])

La 1ére valeur de la série est :  21.5
La dernière valeur de la série est :  18.0

#### Partie 2 – DataFrame

##### 1) Création et affichage du dataframe df_test à partir du dictionnaire suivant

In [36]:
# Création du dictionnaire df_test
data = { 
    "capteur": ["C001", "C002", "C003"], 
    "temperature": [24.5, 25.1, 26.3], 
    "humidite": [65, 67, 70] 
}

In [38]:
# Création et affichagedu DataFrame à partir du dictionnaire data
df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

##### 2) Importation du dataset mesures_capteurs.csv dans le dataframe df

In [53]:
df = pd.read_csv(r'C:\Users\cissc\OneDrive\Documents\P1IA_ODC\atelier_pandas\data\mesures_capteurs.csv')
# On ajoute un 'r' devant les guillemets pour éviter les erreurs de caractères)

##### 3) Affichage les dimensions de df

In [55]:
print("Les dimensions : ", df.shape)

Les dimensions :  (605, 9)

NB : Dans la suite de l’atelier, on travaillera avec le dataframe df

#### Partie 3 – Exploration

##### 1) Affichage des premières lignes

In [57]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

##### 2) Affichage des 10 premières lignes

In [58]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

##### 3) Affichage les dernières lignes

In [59]:
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

##### 4) Affichages des nombre de lignes

In [68]:
nb_lignes = len(df)         #  équivaut nb_lignes = df.shape[0]
print('Nombres de lignes de df : ', nb_lignes)

Nombres de lignes de df :  605

##### 5) Affichage de nombre de colonnes

In [ ]:
nb_colonnes = len(df.columns)       # équivaut  nb_colonnes = df.shape[1]
print('Nombres de colonnes de df : ', nb_colonnes)

Nombres de colonnes de df :  9

##### 6) Affichage des noms des colonnes

In [71]:
print("Noms des colonnes : ",df.columns)

Noms des colonnes :  Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='object')

##### 7) Affichage des informations générales

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    object
 1   date_heure    605 non-null    object
 2   id_capteur    605 non-null    object
 3   batiment      605 non-null    object
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    object
dtypes: float64(4), object(5)
memory usage: 42.7+ KB

##### 8) Affichage des statistiques descriptives

In [73]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

In [74]:
# Variabloes Catégorielles
df.describe(include='object')

       id_mesure           date_heure id_capteur batiment etat
count        605                  605        605      605  601
unique       600                  600         12        4    3
top        M0599  2026-01-29 22:00:00       C002     B001   OK
freq           2                    2         52      153  567

#### Partie 4 – Sélection

##### 1) Sélection de la colonne "temperature"

In [75]:
df['temperature']

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

##### 2) Sélection des colonnes "temperature", "humidite", "pression" et "consommation"

In [77]:
df[["temperature", "humidite", "pression" , "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

##### 3) Sélectionner les 5 premières lignes avec loc

In [79]:
df.loc[:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

##### 4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc

In [81]:
df.iloc[:5]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK