### Atelier Pandas

##### Contexte 
Une entreprise possède plusieurs bâtiments équipés de capteurs IoT. 
Chaque capteur collecte régulièrement des informations sur la température, l'humidité, la pression, 
la consommation énergétique, l'état du capteur, le bâtiment, la date et l'heure de la mesure. 
Les données doivent être préparées et analysées avant d'être transmises à un futur système de 
Machine Learning permettant de détecter des situations anormales.

##### Structuration du projet
        1) Structuration le projet 
        2) Stocker le fichier fourni mesures_capteurs.csv dans le sous-dossier data 
        3) Créer le notebook atelier_pandas_iot.ipynb

In [2]:
import pandas as pd

#### Partie 1 – Series

##### 1) Création d'une Series contenant 4 températures

In [3]:
serie_temp4 = pd.Series([12.25, 38.01, 5.8, 14.5])
serie_temp4

0    12.25
1    38.01
2     5.80
3    14.50
dtype: float64

##### 2) Affichage de l'index de la série

In [4]:
print("L'index de la séerie : ",serie_temp4.index)

L'index de la séerie :  RangeIndex(start=0, stop=4, step=1)

##### 3) Affichage de la 1ère valeur de la série

In [5]:
print("La 1ére valeur de la série est : ", serie_temp4[0])

La 1ére valeur de la série est :  12.25

##### 4) Affichage de la dernière valeur de la série

In [6]:
print("La dernière valeur de la série est : ", serie_temp4.iloc[-1])

La dernière valeur de la série est :  14.5

##### 5) Création de deux façon différentes, une Series de 4 températures avec comme index les heures de mesure 12h, 13h, 14h et 15h

In [7]:
# Première maniére
serie_temp_h = pd.Series([21.5, 32, 7.03, 18], index=['12h', '13h', '14h', '15h'])

# Deuxiéme manière
dict = {'12h' : 21.5, '13h' : 32, '15h' : 7.03, '15h' : 18}
serie_temp_h = pd.Series(dict)
serie_temp_h

12h    21.5
13h    32.0
15h    18.0
dtype: float64

##### 6) Affichage la 1ère et la dernière valeur

In [8]:
# 1e valeur
print("La 1ére valeur de la série est : ", serie_temp_h['12h'])

# dernière valeur
print("La dernière valeur de la série est : ", serie_temp_h.iloc[-1])

La 1ére valeur de la série est :  21.5
La dernière valeur de la série est :  18.0

#### Partie 2 – DataFrame

##### 1) Création et affichage du dataframe df_test à partir du dictionnaire suivant

In [9]:
# Création du dictionnaire df_test
data = { 
    "capteur": ["C001", "C002", "C003"], 
    "temperature": [24.5, 25.1, 26.3], 
    "humidite": [65, 67, 70] 
}

In [10]:
# Création et affichagedu DataFrame à partir du dictionnaire data
df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

##### 2) Importation du dataset mesures_capteurs.csv dans le dataframe df

In [11]:
df = pd.read_csv(r'C:\Users\cissc\OneDrive\Documents\P1IA_ODC\atelier_pandas\data\mesures_capteurs.csv')
# On ajoute un 'r' devant les guillemets pour éviter les erreurs de caractères)

##### 3) Affichage les dimensions de df

In [12]:
print("Les dimensions : ", df.shape)

Les dimensions :  (605, 9)

NB : Dans la suite de l’atelier, on travaillera avec le dataframe df

#### Partie 3 – Exploration

##### 1) Affichage des premières lignes

In [13]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

##### 2) Affichage des 10 premières lignes

In [14]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

##### 3) Affichage les dernières lignes

In [15]:
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

##### 4) Affichages des nombre de lignes

In [16]:
nb_lignes = len(df)         #  équivaut nb_lignes = df.shape[0]
print('Nombres de lignes de df : ', nb_lignes)

Nombres de lignes de df :  605

##### 5) Affichage de nombre de colonnes

In [17]:
nb_colonnes = len(df.columns)       # équivaut  nb_colonnes = df.shape[1]
print('Nombres de colonnes de df : ', nb_colonnes)

Nombres de colonnes de df :  9

##### 6) Affichage des noms des colonnes

In [18]:
print("Noms des colonnes : ",df.columns)

Noms des colonnes :  Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='object')

##### 7) Affichage des informations générales

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    object
 1   date_heure    605 non-null    object
 2   id_capteur    605 non-null    object
 3   batiment      605 non-null    object
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    object
dtypes: float64(4), object(5)
memory usage: 42.7+ KB

##### 8) Affichage des statistiques descriptives

In [20]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

In [21]:
# Variabloes Catégorielles
df.describe(include='object')

       id_mesure           date_heure id_capteur batiment etat
count        605                  605        605      605  601
unique       600                  600         12        4    3
top        M0599  2026-01-29 22:00:00       C002     B001   OK
freq           2                    2         52      153  567

#### Partie 4 – Sélection

##### 1) Sélection de la colonne "temperature"

In [22]:
df['temperature']

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

##### 2) Sélection des colonnes "temperature", "humidite", "pression" et "consommation"

In [23]:
df[["temperature", "humidite", "pression" , "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

##### 3) Sélectionner les 5 premières lignes avec loc

In [24]:
df.loc[:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

##### 4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc

In [25]:
df.iloc[:5]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

#### Partie 5 – Manipulation des colonnes

##### 1) Ajout de la colonne "temperature_fahrenheit"

In [26]:
# formule F = C x (9/5) + 32
df['temperature_fahrenheit'] = (df['temperature'] * (9/5) + 32)
df.head(3)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,temperature_fahrenheit
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476

##### 2) Ajout de la colonne "niveau_temperature" 
"Élevée" (température > 30) ou "Normale". On peut utiliser la méthode where() de numpy

In [27]:
import numpy as np

df['niveau_temperature'] = np.where(df['temperature'] > 30, 'Élevée', 'Normale')
df.head(3)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,temperature_fahrenheit,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476,Normale

##### 3) Renommage de la colonne "humidite" en "humidite_relative"

In [28]:
df = df.rename(columns={'humidite': 'humidite_relative'})
df.head(3)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,temperature_fahrenheit,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476,Normale

##### 4) Suppression de la colonne "temperature_fahrenheit"

In [29]:
df.drop(columns='temperature_fahrenheit', inplace=True)
df.head(3)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,Normale

#### Partie 6 – Filtrage

##### 1) Récupération unique des lignes telles que température > 30

In [30]:
df_tempsup_30 = df[df['temperature'] > 30]
df_tempsup_30.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
63,M0064,2026-01-07 15:00:00,C004,B002,31.19,55.13,1011.04,264.98,OK,Élevée
79,M0275,2026-01-16 10:00:00,C011,B004,31.74,69.95,1020.79,335.89,OK,Élevée

##### 2) Récupération unique des lignes telles que

température > 30 et humidité > 70

In [32]:
df_temp_hum = df[(df['temperature'] > 30) & (df['humidite_relative'] > 70)]
df_temp_hum.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée

#### Partie 7 : Tri

##### 1) Création df_trie1 pour trier en fonction de la température croissante

In [40]:
df_trie1 = df.sort_values('temperature')
df_trie1.head(5)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
487,M0538,2026-01-27 09:00:00,C010,B004,-18.50,66.27,1012.49,312.92,ERREUR,Normale
245,M0127,2026-01-10 06:00:00,C007,B003,14.11,145.00,1032.36,169.57,ERREUR,Normale
258,M0223,2026-01-14 06:00:00,C007,B003,15.49,47.96,1006.34,124.90,OK,Normale
249,M0175,2026-01-12 06:00:00,C007,B003,16.04,55.36,1005.68,140.95,OK,Normale
59,M0146,2026-01-11 01:00:00,C002,B001,16.77,53.44,1010.65,131.75,OK,Normale

##### 2) Création de df_trie2 pour trier en fonction de la température décroissante

In [42]:
df_trie2 = df.sort_values('temperature', ascending=False)
df_trie2.head(5)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée

##### 3) Création de top 10 pour voir les 10 températures les plus élevées

In [44]:
df_temp_top10 = df.nlargest(10, 'temperature')
df_temp_top10

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée
118,M0365,2026-01-20 04:00:00,C005,B002,32.90,65.91,1027.28,246.08,ALERTE,Élevée
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
438,M0558,2026-01-28 05:00:00,C006,B002,32.56,67.77,1016.88,181.51,ALERTE,Élevée
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
169,M0546,2026-01-27 17:00:00,C006,B002,32.36,67.34,998.10,184.89,ALERTE,Élevée

##### 4) Trie en fonction des colonnes "batiment" (croissant) et "temperature" (décroissant)

In [45]:
# Tri par batiment (A -> Z) puis par temperature (Plus chaud -> Plus froid)
df_trie_batemp = df.sort_values(by=['batiment', 'temperature'], ascending=[True, False])
df_trie_batemp.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
447,M0170,2026-01-12 01:00:00,C002,B001,31.15,69.20,1016.10,172.49,OK,Élevée
224,M0303,2026-01-17 14:00:00,C003,B001,30.84,67.98,1020.09,157.99,OK,Élevée
500,M0062,2026-01-07 13:00:00,C002,B001,30.39,52.13,1004.23,262.66,OK,Élevée
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK,Normale

#### Partie 8 : Analyse

##### 1) Affichage de la consommation moyenne par bâtiment

In [47]:
df.groupby('batiment')['consommation'].mean()

batiment
B001    177.870927
B002    221.785333
B003    153.191000
B004    282.552282
Name: consommation, dtype: float64

##### 2) Affichage du minimum, du maximum, de la moyenne et l’écart-type de la température par bâtiment

In [50]:
# Calcul avec des noms de colonnes personnalisés
stats_temp_bat = df.groupby('batiment')['temperature'].agg(
    Minimum = 'min',
    Maximum = 'max',
    Moyenne = 'mean',
    Ecart_Type = 'std'
)

print(stats_temp_bat)

          Minimum  Maximum    Moyenne  Ecart_Type
batiment
B001        16.77    32.72  23.578824    2.961211
B002        17.67    33.60  25.778000    2.951828
B003        14.11    31.74  23.013699    2.983902
B004       -18.50    58.70  27.119000    5.367361

##### 3) Affichage par bâtiment, le maximum et la moyenne de la température et de la consommation

In [54]:
# Agrégation nommée pour chaque colonne spécifique
bat_tempcons = df.groupby('batiment').agg(
    Temp_Max = ('temperature', 'max'),
    Temp_Moyenne = ('temperature', 'mean'),
    Conso_Max = ('consommation', 'max'),
    Conso_Moyenne = ('consommation', 'mean')
)

print(bat_tempcons)

          Temp_Max  Temp_Moyenne  Conso_Max  Conso_Moyenne
batiment
B001         32.72     23.578824     294.72     177.870927
B002         33.60     25.778000     335.20     221.785333
B003         31.74     23.013699     875.00     153.191000
B004         58.70     27.119000     411.12     282.552282

##### 4) Affichage la température moyenne globale

In [59]:
temp_moy_glob = df['temperature'].mean()
print(f"Température moyenne globale : {temp_moy_glob:.2f} °C")

Température moyenne globale : 24.88 °C

##### 5) Affichage de la température maximale

In [61]:
temp_max = df['temperature'].max()
print(f"Température maximale : {temp_max:.2f} °C")

Température maximale : 58.70 °C

##### 6) Affichage de la consommation totale

In [64]:
cons_total = df['consommation'].sum()
print(f"Consommation totale : {cons_total:.3f}")

Consommation totale : 125205.250

##### 7) Quel bâtiment consomme le plus en moyenne ?

In [70]:
# la consommation moyenne par bâtiment
conso_par_batiment = df.groupby('batiment')['consommation'].mean()

# le bâtiment avec la moyenne la plus élevée
batiment_max = conso_par_batiment.idxmax()
valeur_max = conso_par_batiment.max()

print(f"Le bâtiment qui consomme le plus en moyenne est le {batiment_max} avec {valeur_max:.2f}")

Le bâtiment qui consomme le plus en moyenne est le B004 avec 282.55

##### 8) Affichage du nombre d'alertes par bâtiment

In [72]:
nb_alerte = df['etat'].value_counts()
nb_alerte

etat
OK        567
ALERTE     29
ERREUR      5
Name: count, dtype: int64

In [78]:
# les lignes contenant uniquement le mot clé 'ALERTE'
df_alertes = df[df['etat'] == 'ALERTE']

# Compter le nombre de lignes (alertes) pour chaque bâtiment
nb_alertes_par_bat = df_alertes.groupby('batiment').size()

print(nb_alertes_par_bat)

batiment
B001     2
B002     7
B003     5
B004    15
dtype: int64

##### Partie 9 : Gestion des valeurs manquantes

##### 1) Affichage du nombre de valeurs manquantes par colonne

In [83]:
df.isna().sum()

id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           6
humidite_relative     5
pression              5
consommation          5
etat                  4
niveau_temperature    0
dtype: int64

##### 2) Affichage du nombre total des valeurs manquantes

In [84]:
print("Nombres total de valeurs manquantes : ",df.isna().sum().sum())

Nombres total de valeurs manquantes :  25

##### 3) Affichage du taux de valeurs manquantes

In [99]:
# taux de valeurs manquantes pour chaque colonne (en %)
taux_manquants = df.isna().mean() * 100

print("Taux de valeurs manquantes par colonnes")
print(taux_manquants.round(2))

Taux de valeurs manquantes par colonnes
id_mesure             0.00
date_heure            0.00
id_capteur            0.00
batiment              0.00
temperature           0.99
humidite_relative     0.83
pression              0.83
consommation          0.83
etat                  0.66
niveau_temperature    0.00
dtype: float64

In [94]:
print("Taux de valeurs manquantes total: ", taux_manquants.sum().round(2),"%")

Taux de valeurs manquantes total:  4.13 %

##### 4) Affichage des lignes contenant des valeurs manquantes

In [101]:
lignes_manquantes = df[df.isna().any(axis=1)]
lignes_manquantes

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
14,M0056,2026-01-07 07:00:00,C008,B003,22.33,67.42,1014.41,101.20,NaN,Normale
30,M0073,2026-01-08 00:00:00,C001,B001,23.12,63.97,NaN,186.87,OK,Normale
91,M0473,2026-01-24 16:00:00,C005,B002,21.32,70.43,1021.20,194.76,NaN,Normale
128,M0300,2026-01-17 11:00:00,C012,B004,23.32,55.73,NaN,232.38,OK,Normale
139,M0345,2026-01-19 08:00:00,C009,B003,NaN,66.77,1015.33,216.31,OK,Normale
146,M0118,2026-01-09 21:00:00,C010,B004,30.32,NaN,1015.78,261.68,OK,Élevée
149,M0034,2026-01-06 09:00:00,C010,B004,28.91,NaN,1001.23,234.30,OK,Normale
163,M0019,2026-01-05 18:00:00,C007,B003,NaN,69.97,1014.14,181.07,OK,Normale
196,M0372,2026-01-20 11:00:00,C012,B004,29.33,56.91,1020.02,NaN,OK,Normale
215,M0204,2026-01-13 11:00:00,C012,B004,NaN,59.96,1007.98,294.02,OK,Normale
270,M0334,2026-01-18 21:00:00,C010,B004,29.63,67.70,1016.30,363.68,NaN,Normale
303,M0584,2026-01-29 07:00:00,C008,B003,23.78,64.66,NaN,153.81,OK,Normale
307,M0169,2026-01-12 00:00:00,C001,B001,21.86,51.83,NaN,195.72,OK,Normale
323,M0391,2026-01-21 06:00:00,C007,B003,21.82,NaN,1006.47,98.39,OK,Normale
459,M0143,2026-01-10 22:00:00,C011,B004,28.65,66.88,1001.41,NaN,OK,Normale
476,M0527,2026-01-26 22:00:00,C011,B004,26.16,NaN,1024.21,232.87,OK,Normale
490,M0227,2026-01-14 10:00:00,C011,B004,25.13,85.60,1011.20,NaN,ALERTE,Normale
491,M0449,2026-01-23 16:00:00,C005,B002,26.82,61.99,NaN,215.34,OK,Normale
511,M0506,2026-01-26 01:00:00,C002,B001,24.04,57.10,1014.04,NaN,OK,Normale
513,M0490,2026-01-25 09:00:00,C010,B004,NaN,52.97,1010.71,253.63,OK,Normale
526,M0015,2026-01-05 14:00:00,C003,B001,23.17,79.95,1006.07,NaN,OK,Normale
536,M0252,2026-01-15 11:00:00,C012,B004,27.01,NaN,1018.36,263.13,OK,Normale
548,M0572,2026-01-28 19:00:00,C008,B003,NaN,68.63,1018.58,252.48,OK,Normale
556,M0092,2026-01-08 19:00:00,C008,B003,NaN,79.81,1007.05,113.00,OK,Normale
572,M0190,2026-01-12 21:00:00,C010,B004,24.24,73.55,1018.12,299.91,NaN,Normale

#### 5) Pour la température et l’humidité, remplaçons les valeurs manquantes par les moyennes

In [105]:
# Sélection des colonnes cibles et application de fillna avec leur propre moyenne
colonnes_cibles = ['temperature', 'humidite_relative']
df[colonnes_cibles] = df[colonnes_cibles].fillna(df[colonnes_cibles].mean())
df.isna().sum()

id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           0
humidite_relative     0
pression              5
consommation          5
etat                  4
niveau_temperature    0
dtype: int64

##### 6) Pour la consommation, remplacer les valeurs manquantes par la médiane

In [107]:
df['consommation'] = df['consommation'].fillna(df['consommation'].median())
df.isna().sum()

id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           0
humidite_relative     0
pression              5
consommation          0
etat                  4
niveau_temperature    0
dtype: int64

##### 7) Pour "etat", remplaçons les valeurs manquantes par "INCONNU"

In [108]:
df['etat'] = df['etat'].fillna('INCONNU')
df.isna().sum()

id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           0
humidite_relative     0
pression              5
consommation          0
etat                  0
niveau_temperature    0
dtype: int64